apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-proj-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-proj-backend
  template:
    metadata:
      labels:
        app: k8s-proj-backend
    spec:
      containers:
      - name: k8s-proj-backend
        image: sayantannandi/k8s-proj-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: k8s-proj-secrets
              key: db-url
        - name: BACKEND_URL
          valueFrom:
            secretKeyRef:
              name: k8s-proj-secrets
              key: backend-url
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-proj-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-proj-frontend
  template:
    metadata:
      labels:
        app: k8s-proj-frontend
    spec:
      containers:
      - name: k8s-proj-frontend
        image: sayantannandi/k8s-proj-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"