apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-proj-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: k8s-proj.sayantan.space
      http:
        paths:
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: k8s-proj-backend-clusterip-service
                port:
                  number: 3000
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: k8s-proj-frontend-clusterip-service
                port:
                  number: 80